# Generated by Django 5.0.6 on 2024-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusauth', '0004_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='cusauth.role'),
        ),
    ]
