# Generated by Django 4.2.5 on 2024-03-19 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(default=1000000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('pan_no', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('shf_id', models.AutoField(default=2000000, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_credit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount_Debit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('particulars', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlord.person')),
                ('uusersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RDInt',
            fields=[
                ('rd_id', models.AutoField(default=3000000, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlord.person')),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RDColl',
            fields=[
                ('rd_collection_id', models.AutoField(default=400000000, primary_key=True, serialize=False)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('rd_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlord.rdint')),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanInt',
            fields=[
                ('loan_id', models.AutoField(default=5000000, primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('interest_rate', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlord.person')),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanColl',
            fields=[
                ('loan_collection_id', models.AutoField(default=600000000, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('amount_collected', models.DecimalField(decimal_places=3, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('loan_intrest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlord.loanint')),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
