# Generated by Django 4.2.5 on 2024-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancoll',
            name='loan_collection_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loanint',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rdcoll',
            name='rd_collection_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rdint',
            name='rd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='shf_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
