# Generated by Django 4.2.5 on 2024-04-03 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shlord', '0002_alter_loancoll_loan_collection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('sd_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_Debit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlord.person')),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partuclars',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_Debit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount_credit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('particulars', models.TextField(blank=True, null=True)),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
