# Generated by Django 4.2.5 on 2024-04-07 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shlord', '0003_staffsalary_partuclars'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposite',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_Debit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount_credit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('interest_rate', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_no', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_Debit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('debit_date', models.DateTimeField(blank=True, null=True)),
                ('usersf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
