# Generated by Django 4.2.5 on 2024-04-07 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shlord', '0004_fixeddeposite_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposite',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shlord.person'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='amount_Debit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='usersf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fixeddeposite',
            name='amount_Debit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixeddeposite',
            name='amount_credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixeddeposite',
            name='duration',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixeddeposite',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixeddeposite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposite',
            name='usersf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
